apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-processor
  template:
    metadata:
      labels:
        app: email-processor
    spec:
      initContainers:
        - name: wait-for-rabbitmq
          image: busybox
          command: ['sh', '-c', 'until nc -z rabbitmq 5672; do echo waiting for rabbitmq; sleep 2; done;']
      containers:
        - name: email-processor
          image: yudafrid/email-processor:latest
          env:
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
            - name: SPRING_RABBITMQ_USERNAME
              value: guest
            - name: SPRING_RABBITMQ_PASSWORD
              value: guest
            - name: QUEUE_NAME
              value: email-queue
          volumeMounts:
            - name: email-log
              mountPath: /data
      volumes:
        - name: email-log
          persistentVolumeClaim:
            claimName: email-log